
modLoader="javafml" 
loaderVersion="[43,)"
license="LGPLv3"

[[mods]] 
modId="cookyourfood" 
version="1.10"
 
displayURL="https://modrinth.com/mod/cook-your-food"
issueTrackerURL="https://discord.gg/C9MrEenQ"

displayName="Cook your food"
authors="MoonFather" 
description='''This mod makes the food poisoning a serious deal. Eating any kind of raw food will cause poisoning with varying effects. Eating rotten flesh is a very, very bad idea and should only be done as a last-ditch gamble, if you're going to die anyway.''' 
[[dependencies.cookyourfood]]     
    modId="forge"     
    mandatory=true     
    versionRange="[43,)"
    ordering="NONE"    
    side="BOTH"
[[dependencies.cookyourfood]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.19.3)"
    ordering="NONE"
    side="BOTH"

[modproperties.cookyourfood]
    catalogueImageIcon="textures/icon.png"
    configuredBackground="minecraft:textures/block/spruce_planks.png"