
modLoader="javafml" 
loaderVersion="[44,)"
license="LGPLv3"

[[mods]] 
modId="cookyourfood" 
version="1.00" 
 
displayURL="https://modrinth.com/mod/cook-your-food"
issueTrackerURL="https://discord.gg/C9MrEenQ"

displayName="Cook your food"
authors="MoonFather" 
description='''This mod makes the food poisoning a serious deal. Eating any kind of raw food will cause poisoning with varying effects. Eating rotten flesh is a very, very bad idea and should only be done as a last-ditch gamble, if you're going to die anyway.''' 
[[dependencies.cookyourfood]]     
    modId="forge"     
    mandatory=true     
    versionRange="[44,)"
    ordering="NONE"    
    side="BOTH"
[[dependencies.cookyourfood]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
